SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(BOOK_SALES.SALES * BOOK.PRICE) AS TOTAL_SALES
FROM BOOK 
JOIN AUTHOR ON (BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID)
JOIN BOOK_SALES ON (BOOK.BOOK_ID = BOOK_SALES.BOOK_ID)
WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01'
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;