WITH size AS (
    SELECT ID, LENGTH, RANK() OVER(ORDER BY LENGTH DESC) AS ranking
    FROM FISH_INFO
)

SELECT ID, LENGTH
FROM size
WHERE ranking <= 10 AND LENGTH IS NOT NULL 
ORDER BY LENGTH DESC, ID ASC;