-- PARENT_ITEM_ID에 ITEM_ID가 없는 데이터 조회
SELECT ii.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO ii
JOIN ITEM_TREE it ON ii.ITEM_ID = it.ITEM_ID
WHERE NOT EXISTS (SELECT 1 
                  FROM ITEM_TREE sub
                  WHERE sub.PARENT_ITEM_ID  = it.ITEM_ID)
ORDER BY ITEM_ID DESC;