SELECT PRODUCT_CODE, PRICE * SUM(SALES_AMOUNT) AS SALES
FROM PRODUCT p LEFT OUTER JOIN OFFLINE_SALE off ON (p.PRODUCT_ID = off.PRODUCT_ID)
GROUP BY PRODUCT_CODE 
ORDER BY SALES DESC, PRODUCT_CODE ASC;
# 상품코드 별 매출액(판매가 * 판매량) 합계