WITH ani AS (
    SELECT DATEDIFF(ao.DATETIME, ai.DATETIME) AS duration, ai.ANIMAL_ID, ai.NAME
    FROM ANIMAL_INS ai
    JOIN ANIMAL_OUTS ao ON (ai.ANIMAL_ID = ao.ANIMAL_ID)
)
SELECT ANIMAL_ID, NAME
FROM ani
ORDER BY duration DESC
LIMIT 2;