SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (SELECT *, RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS ranking
     FROM REST_INFO) food
WHERE ranking=1
ORDER BY FOOD_TYPE DESC;