-- 크기 내림차순 (큰 것부터 -> CRITICAL, HIGH, MEDIUM, LOW)
WITH RANKING AS (
    SELECT ID, SIZE_OF_COLONY,
        ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS NUM
    FROM ECOLI_DATA
), ECOLI_SIZE AS (
    SELECT ID, 
        (CASE 
            WHEN NUM <= COUNT(*) OVER() * 0.25 THEN 'CRITICAL'
            WHEN NUM <= COUNT(*) OVER() * 0.5 THEN 'HIGH'
            WHEN NUM <= COUNT(*) OVER() * 0.75 THEN 'MEDIUM'
            ELSE 'LOW'
        END) AS CLASS
    FROM RANKING
)

SELECT ID, CLASS AS COLONY_NAME
FROM ECOLI_SIZE
ORDER BY ID ASC;