-- 게시물 3건 이상
SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS "전체주소", REGEXP_REPLACE(TLNO, '^([0-9]{3})([0-9]{4})([0-9]{4})$', '$1-$2-$3') AS "전화번호"
FROM USED_GOODS_BOARD ub
INNER JOIN USED_GOODS_USER uu ON (ub.WRITER_ID = uu.USER_ID)
GROUP BY USER_ID, NICKNAME
HAVING COUNT(ub.BOARD_ID) >= 3
ORDER BY USER_ID DESC;