SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REST_REVIEW.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO RIGHT OUTER JOIN REST_REVIEW ON (REST_INFO.REST_ID = REST_REVIEW.REST_ID)
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_INFO.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;

# 식당 정보 REST_INFO, 테이블과 식당의 리뷰 정보 REST_REVIEW 
# 서울에 위치한 식당들의 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수를 조회