SELECT DATE_FORMAT(SALES_DATE, "%Y") AS YEAR, DATE_FORMAT(SALES_DATE, "%m") AS MONTH, GENDER, COUNT(DISTINCT ui.USER_ID) AS USERS
FROM USER_INFO ui
JOIN ONLINE_SALE os ON (ui.USER_ID = os.USER_ID)
-- 년, 월, 성별 별로 상품을 구매한 회원수를 집계
-- gender가 null이면 제외
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER ASC;