-- 대여기간 행 추가
WITH filter AS(
    SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 AS duration
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT CAR_ID, ROUND(AVG(duration), 1) AS AVERAGE_DURATION
FROM filter 
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;