WITH t_user AS ( -- 2021년에 가입한 회원 수
    SELECT COUNT(*) AS join_member
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)


SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT os.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT os.USER_ID)/tu.join_member, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE os
JOIN USER_INFO ui ON (os.USER_ID = ui.USER_ID)
CROSS JOIN t_user tu
WHERE YEAR(ui.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;