-- 세대별 자식이 없는 대장균의 ID 갯수
WITH RECURSIVE filter AS (
    -- 1세대
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 윗세대의 ID와 현재 부모 ID가 같은 것
    SELECT e.ID, f.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA e
    INNER JOIN filter f ON (e.PARENT_ID = f.ID)
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM filter
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL) -- ()은 CHILD가 있는 대장균의 ID
GROUP BY GENERATION
ORDER BY GENERATION ASC;