-- 세대별 자식이 없는 개체의 세대와 그 수 구하기
WITH RECURSIVE family AS (
    SELECT ID, PARENT_ID, 1 AS depth
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, e.PARENT_ID, depth + 1 AS depth
    FROM ECOLI_DATA e
    INNER JOIN family f ON (f.ID=e.PARENT_ID)
)

SELECT COUNT(*) AS COUNT, depth AS GENERATION
FROM family
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION ASC;