-- 세대 구하고
-- 자식이 없는 개체 구하기
WITH RECURSIVE filter AS (
    SELECT ID, 1 AS GENERATION 
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT ed.ID, f.GENERATION + 1 AS GENERATION 
    FROM ECOLI_DATA ed
    INNER JOIN filter f ON(ed.PARENT_ID = f.ID)
)

SELECT COUNT(*) AS COUNT, f.GENERATION  
FROM filter f
WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION ASC;