WITH number AS (
    SELECT 
        CASE
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN 1
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN 2
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN 3
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 10 AND 12 THEN 4 
        END AS Q
    FROM ECOLI_DATA
)

SELECT CONCAT(Q, 'Q') AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM number
GROUP BY Q
ORDER BY QUARTER ASC;
