SELECT p.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p RIGHT JOIN FOOD_ORDER o ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE EXTRACT(YEAR_MONTH FROM PRODUCE_DATE) = 202205
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;