SELECT HISTORY_ID, 
    ROUND(DAILY_FEE * 
    (1 - COALESCE(dp.DISCOUNT_RATE, 0)/100) * (DATEDIFF(END_DATE, START_DATE)+1))AS FEE
FROM CAR_RENTAL_COMPANY_CAR cc   
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY rh ON (cc.CAR_ID = rh.CAR_ID)
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
    ON (cc.CAR_TYPE = dp.CAR_TYPE)
    AND (
        (DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 >= 7 AND DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 < 30 AND dp.DURATION_TYPE = '7일 이상')
     OR (DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 >= 30 AND DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 < 90 AND dp.DURATION_TYPE = '30일 이상')
     OR (DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 >= 90 AND dp.DURATION_TYPE = '90일 이상')
   )
WHERE cc.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;