SELECT FLAVOR 
FROM (
    SELECT FLAVOR, ROW_NUMBER() OVER (
        ORDER BY SUM(TOTAL_ORDER) DESC
    ) AS rn
    FROM (
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM JULY
    ) AS COMBINE
    GROUP BY FLAVOR
) AS RANKED
WHERE rn <= 3
ORDER BY rn;