SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD ugb JOIN USED_GOODS_USER ugu ON(ugb.WRITER_ID=ugu.USER_ID)
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE)>=700000
ORDER BY TOTAL_SALES ASC;
# 거래총금액 70만원 이상