SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE 
FROM MEMBER_PROFILE mp
LEFT OUTER JOIN REST_REVIEW rr ON (mp.MEMBER_ID = rr.MEMBER_ID)
-- 리뷰를 가장 많이 작성한 회원 찾기(리뷰 개수 - 개수 중 MAX - MAX와 같은 수)
WHERE rr.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(CNT)
        FROM(
            SELECT MEMBER_ID, COUNT(*) AS CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) AS REVIEW_COUNT
    )
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;