-- 부모의 형질을 모두 보유한 대장균
SELECT DISTINCT child.ID, child.GENOTYPE, parent.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA child
INNER JOIN ECOLI_DATA parent ON (child.PARENT_ID = parent.ID)
WHERE child.GENOTYPE & parent.GENOTYPE = parent.GENOTYPE
ORDER BY ID ASC;