-- 자동차 종류가 '세단' AND 10월에 대여를 시작한 기록이 이쓴 자동차
SELECT DISTINCT(cc.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR cc
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY ch ON (cc.CAR_ID = ch.CAR_ID)
WHERE CAR_TYPE = "세단" AND MONTH(START_DATE)='10'
ORDER BY cc.CAR_ID DESC;