WITH filter AS (
    SELECT ID, FISH_NAME, LENGTH, ROW_NUMBER() OVER(PARTITION BY FISH_NAME ORDER BY LENGTH DESC) AS ranking
    FROM FISH_INFO fi
    LEFT JOIN FISH_NAME_INFO fn ON (fi.FISH_TYPE = fn.FISH_TYPE)
)

SELECT ID, FISH_NAME, LENGTH
FROM filter
WHERE ranking = 1
ORDER BY ID ASC;
