WITH user_score AS (
    SELECT SUM(SCORE) AS MYSCORE, he.EMP_NO, he.EMP_NAME, POSITION, EMAIL
    FROM HR_DEPARTMENT hd
    JOIN HR_EMPLOYEES he ON (hd.DEPT_ID=he.DEPT_ID)
    JOIN HR_GRADE hg ON (he.EMP_NO=hg.EMP_NO)
    GROUP BY he.EMP_NO, he.EMP_NAME, POSITION, EMAIL
), ranking AS (
    SELECT MYSCORE, EMP_NO, EMP_NAME, POSITION, EMAIL, RANK() OVER(ORDER BY MYSCORE DESC) AS rn
    FROM user_score
)

SELECT MYSCORE AS SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM ranking
WHERE rn=1
