WITH topview AS (
    SELECT BOARD_ID, RANK() OVER(ORDER BY VIEWS DESC) AS ranking
    FROM USED_GOODS_BOARD
)

SELECT CONCAT("/home/grep/src/", t.BOARD_ID, "/", FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM topview t
JOIN USED_GOODS_FILE uf ON (t.BOARD_ID = uf.BOARD_ID)
WHERE ranking = 1
ORDER BY FILE_ID DESC;