-- 평균 길이가 33cm 이상 (10cm 이하의 물고기들은 10cm로)
WITH LENGTH_FISH AS(
    SELECT ID, if(LENGTH<=10, 10, LENGTH) AS LENGTH, FISH_TYPE
    FROM FISH_INFO
), AVG_FISH AS (
    SELECT FISH_TYPE
    FROM LENGTH_FISH
    GROUP BY FISH_TYPE
    HAVING AVG(LENGTH) >= 33
)

SELECT COUNT(FISH_TYPE) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM LENGTH_FISH
WHERE FISH_TYPE IN (SELECT FISH_TYPE FROM AVG_FISH)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE ASC;