-- 평균 길이가 33cm 이상 (10cm 이하의 물고기들은 10cm로)
WITH AVG_FISH AS (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(IFNULL(LENGTH, 10)) >= 33
)

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (SELECT FISH_TYPE FROM AVG_FISH)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE ASC;