-- 개발자의 스킬
WITH skill AS (
    SELECT *
    FROM DEVELOPERS
    LEFT JOIN SKILLCODES ON (SKILL_CODE & CODE) !=0
)
SELECT (
    CASE
        WHEN SUM(CATEGORY='Front End') > 0 AND SUM(NAME='Python') > 0 THEN 'A'
        WHEN SUM(NAME='C#') > 0 THEN 'B'
        WHEN SUM(CATEGORY='Front End') > 0 THEN 'C'
    END) AS GRADE, ID, EMAIL
FROM skill
GROUP BY ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC;